name: Deploy to GitHub Pages

# Запускаем магию только на пуши в master
on:
  push:
    branches: master
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: true
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish blazor-app.csproj -c Release --output release --nologo
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
        
    - name: Change base-tag in index.html from / to blazor-app
      run: sed -i 's/<base href="\/" \/>/<base href="\/blazor-app\/" \/>/g' release/wwwroot/index.html
      
      # отключаем jekyll
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

      # копируем index.html в 404.html
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
